/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JsVortexStream {
  constructor()
  trades(exchange: string, symbol: string, callback: (arg: string) => void): void
  disconnect(): void
}
